### ISSUE TITLE
Auto search function

### ISSUE THREAD

**Issue by cegbuna** [harveyl888/queryBuilder#5]
Hi,

Great package you’ve built. Is there a functionality to search for a variable by just typing a few characters in the input cells? I have columns with numerous unique names and I have to scroll down the list to find them. Shiny inputs have the ability to search by just entering few characters.

Thanks!

**Comment by harveyl888** [comment]
Hi.  I'm glad this is proving useful!
The select boxes are handled by the underlying jQuery QueryBuilder code.  If selecting with typing were to be implemented I'd want to do it without rewriting the javascript library - for fear of breaking with future releases.  One possibility would be to replace select boxes with jQuery chosen (https://harvesthq.github.io/chosen/).  Not sure if this would work but I'll look into it and see if it's feasible.

**Comment by cegbuna** [comment]
Hi,
Thanks for the prompt response. The select boxes in the link you provided is exactly what I was looking for. Thanks again for looking into this.

Another issue I've encountered is the inability to change the format of the date select box. I'm currently querying from SQL database via RMySQL and the date format it recognizes is '%Y-%m-%d %H:%M:%S'. When I select or pick a date in the date select box, it's in "%Y-%m-%d" and the SQL query doesn't recognize it. Is there a way to format the date select box to reflect the format RMySQL recognizes?

Thanks!

**Comment by harveyl888** [comment]
I think I have a solution to the dropdown selects.  I've implemented jquery chosen and it seems to work for the rule filter.  It needs a little more work if you're interesting in comparing two groups (eg group 1 > group 2).  Checkout the example under https://github.com/harveyl888/queryBuilder/tree/master/inst/examples/example_02.  
Hope this helps!

**Comment by cegbuna** [comment]
I tried the example but the select search doesn't seem to work.

Thanks!

**Comment by cegbuna** [comment]
Your are right, the dropdown selects for rule filter works but not for the input field. Still can't do a dropdown search for the latter.

Thanks,
Emeka

**Comment by harveyl888** [comment]
I'll see what I can do - may have to do it by changing all the select dropdowns in the document.
